#!/bin/bash
# $1 = command
# $2 = search string
CMD=$1
SEARCH=$2

getinfo(){
  set -xv
  virsh list --all
  virsh net-list --all
  virsh pool-list
  set +xv
  for pool in $(virsh pool-list --name); do
    set -xv
    virsh vol-list $pool;
    set +xv
  done
  echo "If you experience timeouts, try to restart your libvirt daemon."
}

nethelp(){
  if [ -z "$SEARCH" ]; then
    virsh net-list --all
    exit 0
  fi
  for net in $(virsh net-list --all --name); do
    if [ -n "$(echo $net | grep -o $SEARCH)" ]; then
      virsh net-destroy $net
      virsh net-undefine $net
    fi
  done
}

destroyDomain(){
  if [ -z "$SEARCH" ]; then
    virsh list --all
    echo "Error: Domain name not provided"
    exit 0
  fi
  for net in $(virsh list --all --name); do
    if [ -n "$(echo $net | grep -o $SEARCH)" ]; then
      virsh snapshot-delete $net --current
      virsh destroy $net
      virsh undefine $net
    fi
  done
  deleteVolumes
}

deleteVolumes(){
  if [ -z "$SEARCH" ]; then
    echo "Error: No search term provided"
    exit 0
  fi
  virsh vol-list default | grep $SEARCH | awk '{print $1}' | xargs -I '{}' virsh vol-delete '{}' default
}

case "${CMD}" in
info)
    getinfo
    ;;
net)
    nethelp
    ;;
delete_volumes)
    deleteVolumes
    ;;
destroy_domain)
    destroyDomain
    ;;
*)
    echo "Usage: vagrant-resolve-issues <command> [search]"
    echo -e "\nAvailable commands:"
    echo -e "  destory_domain name\t Destroys domain with anything in it - Resolve Domain is already taken issue"
    echo -e "  delete_volumes name\t Deletes any images that matches the search term"
    echo -e "  net \t\t\t Shows net-list"
    echo -e "  net search \t\t Undefines every net name that matches the search term"
    echo -e "  info \t\t\t Gives a lot of information that could help resolving problems"
    exit 1
esac
