#!/bin/bash
# $1 = recreate | save | revert

rebuild_machines(){
  echo "This can take a while..."
  echo "Halting all machines"
  vagrant halt
  echo "Deleting old snapshots form current machines"
  libvirt-snapshot remove
  echo "Destroying all machines"
  sudo vagrant destroy -f
  echo "Recreating all machines"
  vagrant up --no-parallel
  vagrant ssh-config > ssh-config
}

create_snapshots(){
  echo "Deleting old snapshots form current machines"
  libvirt-snapshot remove
  echo "Creating new snapshots form current machines"
  libvirt-snapshot create
}

revert_snapshots(){
  echo "Halting all machines"
  vagrant halt
  echo "Reverting machines to last snapshot"
  libvirt-snapshot revert
  echo "Starting machines"
  vagrant up
}

CMD=$1
case "${CMD}" in
rebuild)
    rebuild_machines
    ;;
create)
    create_snapshots
    ;;
revert)
    revert_snapshots
    ;;
*)
    echo "Usage: vagrant-common-actions <command>"
    echo -e "\nAvailable commands:"
    echo -e "  rebuild \t Rebuilds vagrant images and starts them (this takes a long time)"
    echo -e "  create \t Creates snapshots of current machines"
    echo -e "  revert \t Reverts snapshots of machines"
    exit 1
esac

